grep "DirectUI::BaseScrollBar::" dui70_demangled.txt > classes/BaseScrollBar.txt
grep "DirectUI::BaseScrollViewer::" dui70_demangled.txt > classes/BaseScrollViewer.txt
grep "DirectUI::ClassInfoBase::" dui70_demangled.txt > classes/ClassInfoBase.txt
grep "DirectUI::RefcountBase::" dui70_demangled.txt > classes/RefcountBase.txt
grep "DirectUI::Element::" dui70_demangled.txt > classes/Element.txt
grep "DirectUI::ElementWithHWND::" dui70_demangled.txt > classes/ElementWithHWND.txt
grep "DirectUI::UnknownElement::" dui70_demangled.txt > classes/UnknownElement.txt
grep "DirectUI::HWNDElement::" dui70_demangled.txt > classes/HWNDElement.txt
grep "DirectUI::HWNDElementAccessible::" dui70_demangled.txt > classes/HWNDElementAccessible.txt
grep "DirectUI::DialogElement::" dui70_demangled.txt > classes/DialogElement.txt
grep "DirectUI::AnimationStrip::" dui70_demangled.txt > classes/AnimationStrip.txt
grep "DirectUI::RefPointElement::" dui70_demangled.txt > classes/RefPointElement.txt
grep "DirectUI::Button::" dui70_demangled.txt > classes/Button.txt
grep "DirectUI::AutoButton::" dui70_demangled.txt > classes/AutoButton.txt
grep "DirectUI::PushButton::" dui70_demangled.txt > classes/PushButton.txt
grep "DirectUI::RepeatButton::" dui70_demangled.txt > classes/RepeatButton.txt
grep "DirectUI::AccessibleButton::" dui70_demangled.txt > classes/AccessibleButton.txt
grep "DirectUI::Progress::" dui70_demangled.txt > classes/Progress.txt
grep "DirectUI::Page::" dui70_demangled.txt > classes/Page.txt
grep "DirectUI::Pages::" dui70_demangled.txt > classes/Pages.txt
grep "DirectUI::ScrollBar::" dui70_demangled.txt > classes/ScrollBar.txt
grep "DirectUI::Combobox::" dui70_demangled.txt > classes/Combobox.txt
grep "DirectUI::Edit::" dui70_demangled.txt > classes/Edit.txt
grep "DirectUI::Expandable::" dui70_demangled.txt > classes/Expandable.txt
grep "DirectUI::Expando::" dui70_demangled.txt > classes/Expando.txt
grep "DirectUI::XElement::" dui70_demangled.txt > classes/XElement.txt
grep "DirectUI::Layout::" dui70_demangled.txt > classes/Layout.txt
grep "DirectUI::BorderLayout::" dui70_demangled.txt > classes/BorderLayout.txt
grep "DirectUI::GridLayout::" dui70_demangled.txt > classes/GridLayout.txt
grep "DirectUI::FillLayout::" dui70_demangled.txt > classes/FillLayout.txt
grep "DirectUI::FlowLayout::" dui70_demangled.txt > classes/FlowLayout.txt
grep "DirectUI::RowLayout::" dui70_demangled.txt > classes/RowLayout.txt
grep "DirectUI::NineGridLayout::" dui70_demangled.txt > classes/NineGridLayout.txt
grep "DirectUI::ShellBorderLayout::" dui70_demangled.txt > classes/ShellBorderLayout.txt
grep "DirectUI::TableLayout::" dui70_demangled.txt > classes/TableLayout.txt
grep "DirectUI::VerticalFlowLayout::" dui70_demangled.txt > classes/VerticalFlowLayout.txt
grep "DirectUI::CCAVI::" dui70_demangled.txt > classes/CCAVI.txt
grep "DirectUI::CCBase::" dui70_demangled.txt > classes/CCBase.txt
grep "DirectUI::CCBaseCheckRadioButton::" dui70_demangled.txt > classes/CCBaseCheckRadioButton.txt
grep "DirectUI::CCBaseScrollBar::" dui70_demangled.txt > classes/CCBaseScrollBar.txt
grep "DirectUI::CCCheckBox::" dui70_demangled.txt > classes/CCCheckBox.txt
grep "DirectUI::CCCommandLink::" dui70_demangled.txt > classes/CCCommandLink.txt
grep "DirectUI::CCHScrollBar::" dui70_demangled.txt > classes/CCHScrollBar.txt
grep "DirectUI::CCListBox::" dui70_demangled.txt > classes/CCListBox.txt
grep "DirectUI::CCListView::" dui70_demangled.txt > classes/CCListView.txt
grep "DirectUI::CCProgressBar::" dui70_demangled.txt > classes/CCProgressBar.txt
grep "DirectUI::CCPushButton::" dui70_demangled.txt > classes/CCPushButton.txt
grep "DirectUI::CCRadioButton::" dui70_demangled.txt > classes/CCRadioButton.txt
grep "DirectUI::CCSysLink::" dui70_demangled.txt > classes/CCSysLink.txt
grep "DirectUI::CCTrackBar::" dui70_demangled.txt > classes/CCTrackBar.txt
grep "DirectUI::CCTreeView::" dui70_demangled.txt > classes/CCTreeView.txt
grep "DirectUI::CCVScrollBar::" dui70_demangled.txt > classes/CCVScrollBar.txt
grep "DirectUI::CCVScrollBar::" dui70_demangled.txt > classes/CCVScrollBar.txt
grep "DirectUI::CCSysLink::" dui70_demangled.txt > classes/CCSysLink.txt
grep "DirectUI::Browser::" dui70_demangled.txt > classes/Browser.txt
grep "DirectUI::BrowserSelectionProxy::" dui70_demangled.txt > classes/BrowserSelectionProxy.txt
grep "DirectUI::ElementProvider::" dui70_demangled.txt > classes/ElementProvider.txt
grep "DirectUI::ExpandCollapseProvider::" dui70_demangled.txt > classes/ExpandCollapseProvider.txt
grep "DirectUI::GridItemProvider::" dui70_demangled.txt > classes/GridItemProvider.txt
grep "DirectUI::GridProvider::" dui70_demangled.txt > classes/GridProvider.txt
grep "DirectUI::HWNDElementProvider::" dui70_demangled.txt > classes/HWNDElementProvider.txt
grep "DirectUI::InvokeProvider::" dui70_demangled.txt > classes/InvokeProvider.txt
grep "DirectUI::RangeValueProvider::" dui70_demangled.txt > classes/RangeValueProvider.txt
grep "DirectUI::ScrollItemProvider::" dui70_demangled.txt > classes/ScrollItemProvider.txt
grep "DirectUI::ScrollProvider::" dui70_demangled.txt > classes/ScrollProvider.txt
grep "DirectUI::SelectionItemProvider::" dui70_demangled.txt > classes/SelectionItemProvider.txt
grep "DirectUI::SelectionProvider::" dui70_demangled.txt > classes/SelectionProvider.txt
grep "DirectUI::TableItemProvider::" dui70_demangled.txt > classes/TableItemProvider.txt
grep "DirectUI::TableProvider::" dui70_demangled.txt > classes/TableProvider.txt
grep "DirectUI::ToggleProvider::" dui70_demangled.txt > classes/ToggleProvider.txt
grep "DirectUI::ValueProvider::" dui70_demangled.txt > classes/ValueProvider.txt
grep "DirectUI::XProvider::" dui70_demangled.txt > classes/XProvider.txt
grep "DirectUI::XResourceProvider::" dui70_demangled.txt > classes/XResourceProvider.txt
grep "DirectUI::Proxy::" dui70_demangled.txt > classes/Proxy.txt
grep "DirectUI::ElementProxy::" dui70_demangled.txt > classes/ElementProxy.txt
grep "DirectUI::ExpandCollapseProxy::" dui70_demangled.txt > classes/ExpandCollapseProxy.txt
grep "DirectUI::GridItemProxy::" dui70_demangled.txt > classes/GridItemProxy.txt
grep "DirectUI::HWNDElementProxy::" dui70_demangled.txt > classes/HWNDElementProxy.txt
grep "DirectUI::InvokeProxy::" dui70_demangled.txt > classes/InvokeProxy.txt
grep "DirectUI::NavigatorSelectionItemProxy::" dui70_demangled.txt > classes/NavigatorSelectionItemProxy.txt
grep "DirectUI::ProgressRangeValueProxy::" dui70_demangled.txt > classes/ProgressRangeValueProxy.txt
grep "DirectUI::ProviderProxy::" dui70_demangled.txt > classes/ProviderProxy.txt
grep "DirectUI::RangeValueProxy::" dui70_demangled.txt > classes/RangeValueProxy.txt
grep "DirectUI::ScrollBarRangeValueProxy::" dui70_demangled.txt > classes/ScrollBarRangeValueProxy.txt
grep "DirectUI::ScrollItemProxy::" dui70_demangled.txt > classes/ScrollItemProxy.txt
grep "DirectUI::ScrollProxy::" dui70_demangled.txt > classes/ScrollProxy.txt
grep "DirectUI::SelectionItemProxy::" dui70_demangled.txt > classes/SelectionItemProxy.txt
grep "DirectUI::SelectionProxy::" dui70_demangled.txt > classes/SelectionProxy.txt
grep "DirectUI::SelectorSelectionItemProxy::" dui70_demangled.txt > classes/SelectorSelectionItemProxy.txt
grep "DirectUI::SelectorSelectionProxy::" dui70_demangled.txt > classes/SelectorSelectionProxy.txt
grep "DirectUI::TableItemProxy::" dui70_demangled.txt > classes/TableItemProxy.txt
grep "DirectUI::TableProxy::" dui70_demangled.txt > classes/TableProxy.txt
grep "DirectUI::ToggleProxy::" dui70_demangled.txt > classes/ToggleProxy.txt
grep "DirectUI::ValueProxy::" dui70_demangled.txt > classes/ValueProxy.txt
grep "DirectUI::NativeHWNDHost::" dui70_demangled.txt > classes/NativeHWNDHost.txt
grep "DirectUI::HWNDHost::" dui70_demangled.txt > classes/HWNDHost.txt
grep "DirectUI::HWNDHostAccessible::" dui70_demangled.txt > classes/HWNDHostAccessible.txt
grep "DirectUI::HWNDHostClientAccessible::" dui70_demangled.txt > classes/HWNDHostClientAccessible.txt
grep "DirectUI::XHost::" dui70_demangled.txt > classes/XHost.txt
grep "DirectUI::IDataEngine::" dui70_demangled.txt > classes/IDataEngine.txt
grep "DirectUI::IDataEntry::" dui70_demangled.txt > classes/IDataEntry.txt
grep "DirectUI::IProvider::" dui70_demangled.txt > classes/IProvider.txt
grep "DirectUI::ISBLeak::" dui70_demangled.txt > classes/ISBLeak.txt
grep "DirectUI::IXProviderCP::" dui70_demangled.txt > classes/IXProviderCP.txt
grep "DirectUI::IXElementCP::" dui70_demangled.txt > classes/IXElementCP.txt
grep "DirectUI::IElementListener::" dui70_demangled.txt > classes/IElementListener.txt
grep "DirectUI::DUIXmlParser::" dui70_demangled.txt > classes/DUIXmlParser.txt
grep "DirectUI::Schema::" dui70_demangled.txt > classes/Schema.txt
grep "DirectUI::ParserTools::ValueParser::" dui70_demangled.txt > classes/ValueParser.txt
grep "DirectUI::AutoButton::" dui70_demangled.txt > classes/AutoButton.txt
grep "DirectUI::AutoLock::" dui70_demangled.txt > classes/AutoLock.txt
grep "DirectUI::AutoThread::" dui70_demangled.txt > classes/AutoThread.txt
grep "DirectUI::AutoVariant::" dui70_demangled.txt > classes/AutoVariant.txt
grep "DirectUI::CritSecLock::" dui70_demangled.txt > classes/CritSecLock.txt
grep "DirectUI::LinkedList::" dui70_demangled.txt > classes/LinkedList.txt
grep "DirectUI::DeferCycle::" dui70_demangled.txt > classes/DeferCycle.txt
grep "DirectUI::UID::" dui70_demangled.txt > classes/UID.txt
grep "DirectUI::StyleSheet::" dui70_demangled.txt > classes/StyleSheet.txt
grep "DirectUI::Value::" dui70_demangled.txt > classes/Value.txt
grep "DirectUI::Expression::" dui70_demangled.txt > classes/Expression.txt
grep "DirectUI::InvokeHelper::" dui70_demangled.txt > classes/InvokeHelper.txt
grep "DirectUI::ProviderProxy::" dui70_demangled.txt > classes/ProviderProxy.txt
grep "DirectUI::Bind::" dui70_demangled.txt > classes/Bind.txt
grep "DirectUI::CallstackTracker::" dui70_demangled.txt > classes/CallstackTracker.txt
grep "DirectUI::CheckBoxGlyph::" dui70_demangled.txt > classes/CheckBoxGlyph.txt
grep "DirectUI::Clipper::" dui70_demangled.txt > classes/Clipper.txt
grep "DirectUI::DCSurface::" dui70_demangled.txt > classes/DCSurface.txt
grep "DirectUI::DUIFactory::" dui70_demangled.txt > classes/DUIFactory.txt
grep "DirectUI::ExpandoButtonGlyph::" dui70_demangled.txt > classes/ExpandoButtonGlyph.txt
grep "DirectUI::FontCache::" dui70_demangled.txt > classes/FontCache.txt
grep "DirectUI::FontCheckOut::" dui70_demangled.txt > classes/FontCheckOut.txt
grep "DirectUI::Movie::" dui70_demangled.txt > classes/Movie.txt
grep "DirectUI::Navigator::" dui70_demangled.txt > classes/Navigator.txt
grep "DirectUI::Surface::" dui70_demangled.txt > classes/Surface.txt
grep "DirectUI::Thumb::" dui70_demangled.txt > classes/Thumb.txt
grep "DirectUI::Viewer::" dui70_demangled.txt > classes/Viewer.txt
grep "DirectUI::InvokeHelper::" dui70_demangled.txt > classes/InvokeHelper.txt
grep "DirectUI::Macro::" dui70_demangled.txt > classes/Macro.txt
grep "DirectUI::PText::" dui70_demangled.txt > classes/PText.txt
grep "DirectUI::RadioButtonGlyph::" dui70_demangled.txt > classes/RadioButtonGlyph.txt
grep "DirectUI::Repeater::" dui70_demangled.txt > classes/Repeater.txt
grep "DirectUI::ResourceModuleHandles::" dui70_demangled.txt > classes/ResourceModuleHandles.txt
grep "DirectUI::ScrollViewer::" dui70_demangled.txt > classes/ScrollViewer.txt
grep "DirectUI::Selector::" dui70_demangled.txt > classes/Selector.txt
grep "DirectUI::SelectorNoDefault::" dui70_demangled.txt > classes/SelectorNoDefault.txt
grep "DirectUI::StyledScrollViewer::" dui70_demangled.txt > classes/StyledScrollViewer.txt
grep "DirectUI::TaskPage::" dui70_demangled.txt > classes/TaskPage.txt
grep "DirectUI::TextGraphic::" dui70_demangled.txt > classes/TextGraphic.txt
grep "DirectUI::XBaby::" dui70_demangled.txt > classes/XBaby.txt